export const states = [
    { name: "Alabama", value: "AL" },
    { name: "Alaska", value: "AK" },
    { name: "Arizona", value: "AZ" },
    { name: "Arkansas", value: "AR" },
    { name: "California", value: "" }, // empty value example as seen in the screenshot
    { name: "Connecticut", value: "CT" },
    { name: "Delaware", value: "DE" },
    { name: "District of Columbia", value: "DC" },
    { name: "Guam", value: "GU" },
    { name: "Hawaii", value: "HI" },
    { name: "Idaho", value: "ID" },
    { name: "Illinois", value: "IL" },
    { name: "Iowa", value: "IA" },
    { name: "Kansas", value: "KS" },
    { name: "Maryland", value: "MD" },
    { name: "Massachusetts", value: "MA" },
    { name: "Montana", value: "MT" },
    { name: "Nebraska", value: "NE" },
    { name: "New Hampshire", value: "NH" },
    { name: "New Jersey", value: "NJ" },
    { name: "New Mexico", value: "NM" },
    { name: "North Carolina", value: "NC" },
    { name: "North Dakota", value: "ND" },
    { name: "Ohio", value: "OH" },
    { name: "Oklahoma", value: "OK" },
    { name: "Oregon", value: "OR" },
    { name: "Puerto Rico", value: "PR" },
    { name: "Rhode Island", value: "RI" },
    { name: "South Carolina", value: "SC" },
    { name: "Tennessee", value: "TN" },
    { name: "US Virgin Islands", value: "VI" },
    { name: "Vermont", value: "VT" },
    { name: "West Virginia", value: "WV" },
    { name: "Wisconsin", value: "WI" }
]

//Search Type - Licensee - Advanced Criteria

export const licensetype = [
    { value: "X", name: "" },
    { value: "PRO", name: "Insurance Producer" },
    { value: "ADJ", name: "Adjuster" },
    { value: "SRP", name: "Service Representative" },
    { value: "MGA", name: "Managing General Agent" },
    { value: "TIA", name: "Title Insurance Agent" },
    { value: "SLB", name: "Surplus Line Broker" },
    { value: "AA", name: "Apprentice Adjuster" },
    { value: "PES", name: "Portable Electronic Insurance Large" },
    { value: "PEB", name: "Portable Electronic Insurance Small" },
    { value: "PSA", name: "Preneed Sales Agent" },
    { value: "RIN", name: "Reinsurance Intermediary" },
    { value: "TP", name: "Temporary Insurance Producer" },
    { value: "PBM", name: "Pharmacy Benefit Manager" }
];

export const licensestatus = [ //For Alabama state
    { value: "", name: "" },
    { value: "2A", name: "24+ Months Inactive Appointments" },
    { value: "A", name: "Active" },
    { value: "AP", name: "Agent Misrepresented Policy" },
    { value: "AM", name: "Agent Moved" },
    { value: "AR", name: "Agent Request" },
    { value: "AS", name: "Appointed in Error" },
    { value: "AY", name: "Approved" },
    { value: "BC", name: "Bond Cancel" },
    { value: "BN", name: "Non Compliance" },
    { value: "CA", name: "Cancelled" },
    { value: "CI", name: "Company Indebtedness" },
    { value: "CM", name: "Company Merged/Liquidated/Revoked/Suspended" },
    { value: "CR", name: "Company Request" },
    { value: "CT", name: "Converted to Producer" },
    { value: "D", name: "Deceased" },
    { value: "DC", name: "Denied" },
    { value: "DP", name: "Duplicate" },
    { value: "EX", name: "Expired" },
    { value: "FM", name: "Financial Mismanagement" },
    { value: "IA", name: "Inadequate Appointments" },
    { value: "IC", name: "Inactive" },
    { value: "IP", name: "Inappropriate Appointments" },
    { value: "IS", name: "Insufficient Appointments" },
    { value: "MS", name: "Other Agent Misconduct" },
    { value: "PD", name: "Pending Approval" },
    { value: "PE", name: "Pending Rejection" },
    { value: "RJ", name: "Rejected" },
    { value: "SC", name: "Sanctioned by Court" },
    { value: "SP", name: "Suspended" },
    { value: "SY", name: "Surrendered Due to Enforcement" },
    { value: "TA", name: "Temporary Active" },
    { value: "TR", name: "Terminated" },
    { value: "UT", name: "Unknown Reason" },
    { value: "VS", name: "Voluntary Surrender" }
];

export const lineofauthority = [
    { name: "Life", value: "L" },
    { name: "Accident & Health or Sickness", value: "H" },
    { name: "Variable Life and Variable Annuity", value: "V" },
    { name: "Property", value: "P" },
    { name: "Casualty", value: "C" },
    { name: "Automobile (Full Coverage)", value: "A" },
    { name: "Personal Lines", value: "PL" },
    { name: "Bail Bond", value: "BB" },
    { name: "Motor Club", value: "MC" },
    { name: "Dental Services", value: "DS" },
    { name: "Legal Services", value: "LS" },
    { name: "Industrial Fire", value: "IF" },
    { name: "Credit", value: "CR" },
    { name: "Car Rental", value: "RV" },
    { name: "Travel", value: "TRV" },
    { name: "Crop", value: "CP" },
    { name: "Non-resident Reciprocal Surety", value: "NRS" },
    { name: "Self-Service Storage Facilities", value: "SSS" }
  ];
  